export type ArticleType = "article" | "video" | "docs" | "book" | "course" | "tool";
export type ArticleTag = "python" | "typescript" | "git" | "terminal" | "algorithms" | "oop" | "async" | "rest" | "react" | "nodejs" | "sql" | "docker" | "security" | "cleancode" | "career" | "javascript" | "css" | "networks" | "architecture";

export interface Article {
  id: string;
  title: string;
  description: string;
  href: string;
  type: ArticleType;
  tags: ArticleTag[];
  lang: "pt" | "en";
  free: boolean;
  level: "iniciante" | "intermediário" | "avançado";
}

export const articles: Article[] = [
  // ─── PYTHON ───────────────────────────────────────────
  {
    id: "py-1",
    title: "Python Tutorial Oficial",
    description: "A documentação oficial do Python, do básico ao intermediário. Melhor fonte possível.",
    href: "https://docs.python.org/3/tutorial/",
    type: "docs",
    tags: ["python"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "py-2",
    title: "Real Python — Getting Started",
    description: "Coleção de tutoriais práticos de Python escritos por experts. Um dos melhores sites.",
    href: "https://realpython.com/start-here/",
    type: "article",
    tags: ["python"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "py-3",
    title: "Python OOP com exemplos reais",
    description: "Tutorial completo sobre classes, herança, polimorfismo e encapsulamento em Python.",
    href: "https://realpython.com/python3-object-oriented-programming/",
    type: "article",
    tags: ["python", "oop"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "py-4",
    title: "Async IO em Python — Guia Completo",
    description: "Tudo sobre asyncio, async/await, event loop e como Python lida com concorrência.",
    href: "https://realpython.com/async-io-python/",
    type: "article",
    tags: ["python", "async"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "py-5",
    title: "Python Type Hints — Guia Prático",
    description: "Como usar tipagem estática no Python com typing, dataclasses e Pydantic.",
    href: "https://realpython.com/python-type-checking/",
    type: "article",
    tags: ["python"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "py-6",
    title: "FastAPI — Tutorial Oficial",
    description: "Tutorial oficial do FastAPI — do zero ao deploy, com exemplos e boas práticas.",
    href: "https://fastapi.tiangolo.com/tutorial/",
    type: "docs",
    tags: ["python"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "py-7",
    title: "Pytest — Getting Started",
    description: "Como escrever testes em Python com pytest, fixtures, mocks e coverage.",
    href: "https://docs.pytest.org/en/stable/getting-started.html",
    type: "docs",
    tags: ["python"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "py-8",
    title: "List Comprehensions em Python",
    description: "Aprenda a usar list comprehensions, dict comprehensions e generator expressions.",
    href: "https://realpython.com/list-comprehension-python/",
    type: "article",
    tags: ["python"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "py-9",
    title: "Python Decorators — Como Funcionam",
    description: "Entenda decorators de dentro para fora com exemplos práticos e casos de uso reais.",
    href: "https://realpython.com/primer-on-python-decorators/",
    type: "article",
    tags: ["python"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "py-10",
    title: "Automate the Boring Stuff (livro grátis)",
    description: "Livro gratuito online. Aprenda Python resolvendo problemas reais do dia a dia.",
    href: "https://automatetheboringstuff.com/",
    type: "book",
    tags: ["python"],
    lang: "en",
    free: true,
    level: "iniciante",
  },

  // ─── TYPESCRIPT ────────────────────────────────────────
  {
    id: "ts-1",
    title: "TypeScript Handbook Oficial",
    description: "A documentação oficial do TypeScript. Começa pelo handbook, é muito bem escrita.",
    href: "https://www.typescriptlang.org/docs/handbook/intro.html",
    type: "docs",
    tags: ["typescript"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "ts-2",
    title: "TypeScript em 5 minutos",
    description: "Intro rápida ao TypeScript para quem já sabe JavaScript.",
    href: "https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html",
    type: "docs",
    tags: ["typescript"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "ts-3",
    title: "Total TypeScript — Free Tutorials",
    description: "Matt Pocock é o melhor professor de TypeScript. Tutoriais gratuitos excelentes.",
    href: "https://www.totaltypescript.com/tutorials",
    type: "course",
    tags: ["typescript"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "ts-4",
    title: "TypeScript Generics Explicados",
    description: "Guia visual e prático para entender generics, constraints e utility types.",
    href: "https://www.totaltypescript.com/typescript-generics",
    type: "article",
    tags: ["typescript"],
    lang: "en",
    free: true,
    level: "avançado",
  },
  {
    id: "ts-5",
    title: "Execute Program — TypeScript",
    description: "Aprenda TypeScript escrevendo código real em exercícios interativos no browser.",
    href: "https://www.executeprogram.com/courses/typescript",
    type: "course",
    tags: ["typescript"],
    lang: "en",
    free: false,
    level: "iniciante",
  },
  {
    id: "ts-6",
    title: "Zod — Validação em TypeScript",
    description: "Como usar Zod para validar dados no TypeScript de forma type-safe.",
    href: "https://zod.dev/",
    type: "docs",
    tags: ["typescript"],
    lang: "en",
    free: true,
    level: "intermediário",
  },

  // ─── GIT ───────────────────────────────────────────────
  {
    id: "git-1",
    title: "Pro Git Book (grátis online)",
    description: "O livro definitivo sobre Git. Disponível gratuitamente online. Fundamental.",
    href: "https://git-scm.com/book/en/v2",
    type: "book",
    tags: ["git"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "git-2",
    title: "Atlassian Git Tutorial",
    description: "Tutorial visual e completo sobre Git. Branches, merges, rebases com diagramas.",
    href: "https://www.atlassian.com/git/tutorials",
    type: "article",
    tags: ["git"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "git-3",
    title: "Oh My Git! — Jogo para aprender Git",
    description: "Jogo interativo open-source que ensina Git de forma visual. Muito bom para iniciantes.",
    href: "https://ohmygit.org/",
    type: "tool",
    tags: ["git"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "git-4",
    title: "Conventional Commits",
    description: "Padrão de mensagens de commit usado em todo mercado. Essencial para trabalho em equipe.",
    href: "https://www.conventionalcommits.org/",
    type: "docs",
    tags: ["git"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "git-5",
    title: "Learn Git Branching (interativo)",
    description: "O melhor jeito de aprender branches, rebase e merge. Visual e interativo no browser.",
    href: "https://learngitbranching.js.org/?locale=pt_BR",
    type: "tool",
    tags: ["git"],
    lang: "pt",
    free: true,
    level: "iniciante",
  },

  // ─── TERMINAL ──────────────────────────────────────────
  {
    id: "term-1",
    title: "The Missing Semester (MIT)",
    description: "Curso do MIT sobre ferramentas que nenhuma faculdade ensina: shell, vim, git, SSH.",
    href: "https://missing.csail.mit.edu/",
    type: "course",
    tags: ["terminal"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "term-2",
    title: "Explainshell — Entenda qualquer comando",
    description: "Cole qualquer comando de terminal e veja o que cada parte significa. Ferramenta incrível.",
    href: "https://explainshell.com/",
    type: "tool",
    tags: ["terminal"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "term-3",
    title: "Linux Command Line — Tutorial completo",
    description: "Referência completa de comandos de terminal para Linux/Mac/WSL.",
    href: "https://linuxcommand.org/lc3_learning_the_shell.php",
    type: "article",
    tags: ["terminal"],
    lang: "en",
    free: true,
    level: "iniciante",
  },

  // ─── ALGORITMOS ────────────────────────────────────────
  {
    id: "alg-1",
    title: "CS50x — Harvard (grátis)",
    description: "O melhor curso de introdução à ciência da computação. Grátis, com certificado pago.",
    href: "https://cs50.harvard.edu/x/",
    type: "course",
    tags: ["algorithms"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "alg-2",
    title: "LeetCode — Problemas fáceis por categoria",
    description: "Top 150 problemas do LeetCode para entrevistas. Comece pelos fáceis.",
    href: "https://leetcode.com/studyplan/top-interview-150/",
    type: "tool",
    tags: ["algorithms"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "alg-3",
    title: "Visualgo — Algoritmos visualizados",
    description: "Visualização animada de estruturas de dados e algoritmos. Ótimo para entender.",
    href: "https://visualgo.net/",
    type: "tool",
    tags: ["algorithms"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "alg-4",
    title: "Big-O Cheat Sheet",
    description: "Tabela de complexidade de todos os algoritmos e estruturas de dados comuns.",
    href: "https://www.bigocheatsheet.com/",
    type: "tool",
    tags: ["algorithms"],
    lang: "en",
    free: true,
    level: "iniciante",
  },

  // ─── ASYNC ─────────────────────────────────────────────
  {
    id: "async-1",
    title: "JavaScript Event Loop Visualizado",
    description: "Philip Roberts explica o event loop de forma visual. Palestra clássica e obrigatória.",
    href: "https://www.youtube.com/watch?v=8aGhZQkoFbQ",
    type: "video",
    tags: ["async", "nodejs"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "async-2",
    title: "Promises em JS — MDN",
    description: "Documentação oficial do MDN sobre Promises, async/await e tratamento de erros.",
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises",
    type: "docs",
    tags: ["async", "typescript"],
    lang: "en",
    free: true,
    level: "intermediário",
  },

  // ─── REST & HTTP ───────────────────────────────────────
  {
    id: "rest-1",
    title: "HTTP Cats — Status codes explicados",
    description: "Aprenda os status codes HTTP de forma divertida. Referência rápida.",
    href: "https://http.cat/",
    type: "tool",
    tags: ["rest"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "rest-2",
    title: "RESTful API Design — Melhores práticas",
    description: "Guia de boas práticas para design de APIs REST. Versionamento, nomenclatura, erros.",
    href: "https://restfulapi.net/",
    type: "article",
    tags: ["rest"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "rest-3",
    title: "HTTP in detail — How it works",
    description: "Explicação detalhada de como o HTTP funciona por baixo dos panos.",
    href: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview",
    type: "docs",
    tags: ["rest"],
    lang: "en",
    free: true,
    level: "iniciante",
  },

  // ─── REACT ─────────────────────────────────────────────
  {
    id: "react-1",
    title: "React.dev — Documentação Oficial",
    description: "A nova documentação oficial do React com exemplos interativos. Começa aqui.",
    href: "https://react.dev/learn",
    type: "docs",
    tags: ["react"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "react-2",
    title: "React Hooks — Guia visual",
    description: "useState, useEffect, useCallback, useMemo explicados com diagramas.",
    href: "https://www.joshwcomeau.com/react/hooks-cheat-sheet/",
    type: "article",
    tags: ["react"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "react-3",
    title: "Just JavaScript — Dan Abramov",
    description: "Mental models para JavaScript e React do criador do Redux. Email course.",
    href: "https://justjavascript.com/",
    type: "course",
    tags: ["react", "typescript"],
    lang: "en",
    free: true,
    level: "iniciante",
  },

  // ─── NODE.JS ───────────────────────────────────────────
  {
    id: "node-1",
    title: "Node.js Official Docs",
    description: "Documentação oficial do Node.js. Referência para todos os módulos built-in.",
    href: "https://nodejs.org/en/docs/",
    type: "docs",
    tags: ["nodejs"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "node-2",
    title: "Node.js Best Practices",
    description: "Repositório com 80+ boas práticas para Node.js em produção.",
    href: "https://github.com/goldbergyoni/nodebestpractices",
    type: "article",
    tags: ["nodejs"],
    lang: "en",
    free: true,
    level: "intermediário",
  },

  // ─── SQL ───────────────────────────────────────────────
  {
    id: "sql-1",
    title: "SQLZoo — SQL interativo",
    description: "Aprenda SQL escrevendo queries reais diretamente no browser. Ótimo para começar.",
    href: "https://sqlzoo.net/",
    type: "tool",
    tags: ["sql"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "sql-2",
    title: "PostgreSQL Tutorial",
    description: "Tutorial completo de PostgreSQL do básico ao avançado com exemplos.",
    href: "https://www.postgresqltutorial.com/",
    type: "article",
    tags: ["sql"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "sql-3",
    title: "SQLBolt — Exercícios interativos",
    description: "Exercícios práticos de SQL no browser, do SELECT básico a JOINs complexos.",
    href: "https://sqlbolt.com/",
    type: "tool",
    tags: ["sql"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "sql-4",
    title: "Prisma Docs — Getting Started",
    description: "ORM moderno para TypeScript. Tutorial completo com PostgreSQL.",
    href: "https://www.prisma.io/docs/getting-started",
    type: "docs",
    tags: ["sql", "typescript"],
    lang: "en",
    free: true,
    level: "intermediário",
  },

  // ─── DOCKER ────────────────────────────────────────────
  {
    id: "docker-1",
    title: "Play with Docker — Labs interativos",
    description: "Pratique Docker diretamente no browser sem instalar nada. Sandbox gratuito.",
    href: "https://labs.play-with-docker.com/",
    type: "tool",
    tags: ["docker"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "docker-2",
    title: "Docker — Get Started Oficial",
    description: "Tutorial oficial do Docker do zero. Containers, imagens, volumes e compose.",
    href: "https://docs.docker.com/get-started/",
    type: "docs",
    tags: ["docker"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "docker-3",
    title: "Docker Compose — Tutorial Prático",
    description: "Como usar docker-compose para orquestrar app + banco + cache juntos.",
    href: "https://docs.docker.com/compose/gettingstarted/",
    type: "docs",
    tags: ["docker"],
    lang: "en",
    free: true,
    level: "intermediário",
  },

  // ─── SEGURANÇA ─────────────────────────────────────────
  {
    id: "sec-1",
    title: "OWASP Top 10 — 2021",
    description: "Os 10 vulnerabilidades mais críticas em aplicações web. Todo dev precisa conhecer.",
    href: "https://owasp.org/www-project-top-ten/",
    type: "docs",
    tags: ["security"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "sec-2",
    title: "HacksPlaining — Aprenda ataques web",
    description: "Tutoriais interativos sobre XSS, SQLi, CSRF e outros ataques. Excelente.",
    href: "https://www.hacksplaining.com/",
    type: "tool",
    tags: ["security"],
    lang: "en",
    free: true,
    level: "iniciante",
  },

  // ─── CLEAN CODE ────────────────────────────────────────
  {
    id: "clean-1",
    title: "Clean Code — Resumo dos princípios",
    description: "Resumo prático dos princípios do livro Clean Code aplicados a Python e JS.",
    href: "https://github.com/ryanmcdermott/clean-code-javascript",
    type: "article",
    tags: ["cleancode"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "clean-2",
    title: "SOLID Principles Explicados",
    description: "Os 5 princípios SOLID com exemplos práticos em Python e TypeScript.",
    href: "https://realpython.com/solid-principles-python/",
    type: "article",
    tags: ["cleancode", "oop"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "clean-3",
    title: "Refactoring Guru — Design Patterns",
    description: "Catálogo visual dos design patterns clássicos com exemplos em várias linguagens.",
    href: "https://refactoring.guru/design-patterns",
    type: "article",
    tags: ["cleancode"],
    lang: "en",
    free: true,
    level: "avançado",
  },

  // ─── CARREIRA ──────────────────────────────────────────
  {
    id: "career-1",
    title: "roadmap.sh — Developer Roadmaps",
    description: "Mapas visuais de carreira para qualquer stack. Frontend, backend, DevOps e mais.",
    href: "https://roadmap.sh/",
    type: "tool",
    tags: ["career"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "career-2",
    title: "Como montar um README incrível no GitHub",
    description: "Guia completo para criar um perfil GitHub que impressiona recrutadores.",
    href: "https://github.com/abhisheknaiidu/awesome-github-profile-readme",
    type: "article",
    tags: ["career"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "career-3",
    title: "Como passar em entrevistas técnicas",
    description: "Guia prático sobre coding interviews, system design e perguntas comportamentais.",
    href: "https://www.techinterviewhandbook.org/",
    type: "article",
    tags: ["career"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "career-4",
    title: "Como contribuir para Open Source",
    description: "Guia passo a passo para fazer sua primeira contribuição open source no GitHub.",
    href: "https://opensource.guide/how-to-contribute/",
    type: "article",
    tags: ["career"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "career-5",
    title: "Developer Roadmap em PT-BR (Filipe Deschamps)",
    description: "Vídeo do Filipe Deschamps sobre o que aprender para ser dev em 2024/2025.",
    href: "https://www.youtube.com/@FilipeDeschamps",
    type: "video",
    tags: ["career"],
    lang: "pt",
    free: true,
    level: "iniciante",
  },

  // ─── JAVASCRIPT ────────────────────────────────────────
  {
    id: "js-1",
    title: "javascript.info — A Bíblia do JS",
    description: "O tutorial mais completo de JavaScript moderno. Do zero a expert. Referência absoluta.",
    href: "https://javascript.info/",
    type: "article",
    tags: ["javascript"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "js-2",
    title: "Eloquent JavaScript (livro grátis)",
    description: "Livro clássico de JavaScript disponível online gratuitamente. Profundo e prático.",
    href: "https://eloquentjavascript.net/",
    type: "book",
    tags: ["javascript"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "js-3",
    title: "You Don't Know JS (série grátis)",
    description: "Série de livros gratuitos que explica JavaScript do jeito que ele realmente funciona.",
    href: "https://github.com/getify/You-Dont-Know-JS",
    type: "book",
    tags: ["javascript"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "js-4",
    title: "JavaScript30 — 30 projetos em 30 dias",
    description: "Wes Bos. 30 mini-projetos com JavaScript puro. Sem frameworks, sem libs. Excelente para prática.",
    href: "https://javascript30.com/",
    type: "course",
    tags: ["javascript"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "js-5",
    title: "MDN — JavaScript Guide",
    description: "Guia oficial de JavaScript da MDN. Referência completa e confiável para qualquer dúvida.",
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    type: "docs",
    tags: ["javascript", "async"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "js-6",
    title: "Fireship — JavaScript em 100 segundos",
    description: "Vídeos rápidos e densos sobre conceitos de JS. Canal essencial para devs modernos.",
    href: "https://www.youtube.com/@Fireship",
    type: "video",
    tags: ["javascript", "typescript", "react"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "js-7",
    title: "Loupe — Event Loop Visualizado",
    description: "Ferramenta interativa que mostra o event loop, call stack e callback queue em tempo real.",
    href: "http://latentflip.com/loupe/",
    type: "tool",
    tags: ["javascript", "async"],
    lang: "en",
    free: true,
    level: "iniciante",
  },

  // ─── CSS ───────────────────────────────────────────────
  {
    id: "css-1",
    title: "CSS Tricks — Guia Completo",
    description: "Referência mais usada para CSS. Flexbox, Grid, animações, pseudo-elementos e muito mais.",
    href: "https://css-tricks.com/",
    type: "article",
    tags: ["css"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "css-2",
    title: "Flexbox Froggy — Jogo interativo",
    description: "Aprenda Flexbox colocando sapos no lugar certo. 24 níveis progressivos. Melhor jeito de fixar.",
    href: "https://flexboxfroggy.com/",
    type: "tool",
    tags: ["css"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "css-3",
    title: "Grid Garden — CSS Grid interativo",
    description: "Aprenda CSS Grid cultivando um jardim. 28 níveis do básico ao avançado.",
    href: "https://cssgridgarden.com/",
    type: "tool",
    tags: ["css"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "css-4",
    title: "Kevin Powell — CSS no YouTube",
    description: "Melhor canal de CSS do YouTube. Flexbox, Grid, layout responsivo com exemplos reais.",
    href: "https://www.youtube.com/@KevinPowell",
    type: "video",
    tags: ["css"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "css-5",
    title: "web.dev — Learn CSS (Google)",
    description: "Curso completo de CSS do Google. Módulos independentes, bem organizados e modernos.",
    href: "https://web.dev/learn/css/",
    type: "course",
    tags: ["css"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "css-6",
    title: "A Complete Guide to Flexbox",
    description: "O guia visual mais famoso de Flexbox. Todos os valores e propriedades com exemplos visuais.",
    href: "https://css-tricks.com/snippets/css/a-guide-to-flexbox/",
    type: "article",
    tags: ["css"],
    lang: "en",
    free: true,
    level: "iniciante",
  },

  // ─── REDES & INTERNET ──────────────────────────────────
  {
    id: "net-1",
    title: "How DNS Works (história em quadrinhos)",
    description: "Explicação visual de como o DNS funciona — do browser até o servidor e de volta. Imperdível.",
    href: "https://howdns.works/",
    type: "article",
    tags: ["networks"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "net-2",
    title: "HTTP — MDN Overview Completo",
    description: "Como o HTTP funciona: métodos, headers, status codes, cookies, caching e HTTPS.",
    href: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview",
    type: "docs",
    tags: ["networks", "rest"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "net-3",
    title: "High Performance Browser Networking (grátis)",
    description: "Livro do Google sobre TCP, UDP, TLS, HTTP/2, WebSockets, WebRTC. Leitura obrigatória para backend.",
    href: "https://hpbn.co/",
    type: "book",
    tags: ["networks"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "net-4",
    title: "Cloudflare Learning Center",
    description: "Explicações excelentes sobre DNS, CDN, DDoS, TLS, HTTP/3, load balancing e mais.",
    href: "https://www.cloudflare.com/learning/",
    type: "article",
    tags: ["networks", "security"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "net-5",
    title: "Como browsers funcionam — web.dev",
    description: "Artigo técnico do Google explicando rendering, parsing HTML/CSS, layout e paint.",
    href: "https://web.dev/articles/howbrowserswork",
    type: "article",
    tags: ["networks"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "net-6",
    title: "WebSockets em detalhes — MDN",
    description: "Como funciona o protocolo WebSocket, quando usar vs HTTP, exemplos de código.",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API",
    type: "docs",
    tags: ["networks", "async"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "net-7",
    title: "Bash.ws — Networking tools online",
    description: "DNS lookup, ping, traceroute, whois e mais — tudo online. Útil para entender redes na prática.",
    href: "https://bash.ws/",
    type: "tool",
    tags: ["networks"],
    lang: "en",
    free: true,
    level: "iniciante",
  },

  // ─── ARQUITETURA ───────────────────────────────────────
  {
    id: "arch-1",
    title: "System Design Primer (GitHub)",
    description: "O guia mais completo de system design. Escalabilidade, load balancers, cache, filas. 200k+ stars.",
    href: "https://github.com/donnemartin/system-design-primer",
    type: "article",
    tags: ["architecture"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "arch-2",
    title: "Microservices.io — Padrões e anti-padrões",
    description: "Catálogo de padrões de microservices por Chris Richardson. API Gateway, CQRS, Saga, Event Sourcing.",
    href: "https://microservices.io/patterns/",
    type: "article",
    tags: ["architecture"],
    lang: "en",
    free: true,
    level: "avançado",
  },
  {
    id: "arch-3",
    title: "Roadmap.sh — Backend (visual)",
    description: "Mapa visual de tudo que um dev backend precisa saber. Ótimo para ver onde você está.",
    href: "https://roadmap.sh/backend",
    type: "tool",
    tags: ["architecture", "career"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "arch-4",
    title: "Martin Fowler — Padrões e Arquitetura",
    description: "Artigos do maior nome em arquitetura de software. Refactoring, patterns, microservices.",
    href: "https://martinfowler.com/",
    type: "article",
    tags: ["architecture", "cleancode"],
    lang: "en",
    free: true,
    level: "avançado",
  },
  {
    id: "arch-5",
    title: "ByteByteGo — System Design no YouTube",
    description: "Canal do Alex Xu. Animações excelentes explicando como Twitter, YouTube, WhatsApp funcionam.",
    href: "https://www.youtube.com/@ByteByteGo",
    type: "video",
    tags: ["architecture"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "arch-6",
    title: "12 Factor App",
    description: "Metodologia para construir aplicações SaaS escaláveis e portáveis. Padrão da indústria.",
    href: "https://12factor.net/",
    type: "docs",
    tags: ["architecture", "docker"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "arch-7",
    title: "Roadmap.sh — Frontend (visual)",
    description: "Mapa completo de dev frontend. HTML, CSS, JS, React, performance, acessibilidade.",
    href: "https://roadmap.sh/frontend",
    type: "tool",
    tags: ["architecture", "career"],
    lang: "en",
    free: true,
    level: "iniciante",
  },

  // ─── MAIS ALGORITMOS & LÓGICA ──────────────────────────
  {
    id: "alg-5",
    title: "Neetcode.io — Roadmap + Vídeos",
    description: "Melhor canal/site para LeetCode. Roadmap estruturado + explicações em vídeo de cada problema.",
    href: "https://neetcode.io/",
    type: "course",
    tags: ["algorithms"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "alg-6",
    title: "HackerRank — Trilhas por linguagem",
    description: "Exercícios práticos organizados por linguagem e tema. Boa alternativa ao LeetCode para iniciantes.",
    href: "https://www.hackerrank.com/domains/python",
    type: "tool",
    tags: ["algorithms", "python"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "alg-7",
    title: "Exercism — Exercícios com mentoria",
    description: "Plataforma de exercícios com mentoria real. Tem trilhas de Python e TypeScript excelentes.",
    href: "https://exercism.org/",
    type: "tool",
    tags: ["algorithms", "python", "typescript"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "alg-8",
    title: "Codewars — Kata por dificuldade",
    description: "Plataforma gamificada de desafios de código. 8kyu a 1kyu. Bom para manter consistência.",
    href: "https://www.codewars.com/",
    type: "tool",
    tags: ["algorithms"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "alg-9",
    title: "Grind 75 — LeetCode estruturado",
    description: "Seleção curada dos 75 problemas mais importantes do LeetCode, organizados por semana.",
    href: "https://www.techinterviewhandbook.org/grind75",
    type: "tool",
    tags: ["algorithms", "career"],
    lang: "en",
    free: true,
    level: "intermediário",
  },

  // ─── MAIS PYTHON ───────────────────────────────────────
  {
    id: "py-11",
    title: "Python Tutor — Visualize execução linha a linha",
    description: "Visualize o que acontece na memória ao executar seu código Python. Perfeito para entender loops e recursão.",
    href: "https://pythontutor.com/",
    type: "tool",
    tags: ["python", "algorithms"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "py-12",
    title: "Talk Python to Me — Podcast",
    description: "Podcast semanal sobre Python com os maiores especialistas. Cobre desde web até ciência de dados.",
    href: "https://talkpython.fm/",
    type: "article",
    tags: ["python"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "py-13",
    title: "roadmap.sh/python — Mapa visual",
    description: "Mapa visual de tudo que um dev Python precisa saber. Do básico ao avançado.",
    href: "https://roadmap.sh/python",
    type: "tool",
    tags: ["python", "career"],
    lang: "en",
    free: true,
    level: "iniciante",
  },

  // ─── MAIS TYPESCRIPT / REACT ───────────────────────────
  {
    id: "ts-7",
    title: "TypeScript Deep Dive (livro grátis)",
    description: "Basarat Ali Syed. Livro gratuito e completo de TypeScript. Muito usado como referência.",
    href: "https://basarat.gitbook.io/typescript/",
    type: "book",
    tags: ["typescript"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "ts-8",
    title: "Type Challenges — Desafios de tipo",
    description: "Repositório com 100+ desafios de TypeScript do iniciante ao insano. Melhor forma de dominar tipos.",
    href: "https://github.com/type-challenges/type-challenges",
    type: "tool",
    tags: ["typescript"],
    lang: "en",
    free: true,
    level: "avançado",
  },
  {
    id: "react-4",
    title: "Patterns.dev — Padrões React modernos",
    description: "Catálogo visual de padrões de design para React: compound components, render props, hooks e mais.",
    href: "https://www.patterns.dev/",
    type: "article",
    tags: ["react", "javascript"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "react-5",
    title: "TanStack Query (React Query) Docs",
    description: "Gerenciamento de estado assíncrono para React. Padrão da indústria para fetch de dados.",
    href: "https://tanstack.com/query/latest/docs/framework/react/overview",
    type: "docs",
    tags: ["react", "async"],
    lang: "en",
    free: true,
    level: "intermediário",
  },

  // ─── FERRAMENTAS & WORKFLOW ────────────────────────────
  {
    id: "tool-1",
    title: "Postman — Testar APIs",
    description: "Ferramenta padrão para testar e documentar APIs REST. Indispensável no dia a dia.",
    href: "https://www.postman.com/",
    type: "tool",
    tags: ["rest"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
  {
    id: "tool-2",
    title: "GitHub Actions — CI/CD Docs",
    description: "Automatize builds, testes e deploys diretamente no GitHub. Padrão de CI/CD para projetos open source.",
    href: "https://docs.github.com/en/actions",
    type: "docs",
    tags: ["docker", "git"],
    lang: "en",
    free: true,
    level: "intermediário",
  },
  {
    id: "tool-3",
    title: "Regex101 — Testar expressões regulares",
    description: "Editor e tester de regex online com explicação de cada parte. Suporta Python, JS e mais.",
    href: "https://regex101.com/",
    type: "tool",
    tags: ["python", "javascript"],
    lang: "en",
    free: true,
    level: "iniciante",
  },
];

export const allTags: { value: ArticleTag | "all"; label: string }[] = [
  { value: "all",          label: "Todos" },
  { value: "python",       label: "Python" },
  { value: "javascript",   label: "JavaScript" },
  { value: "typescript",   label: "TypeScript" },
  { value: "css",          label: "CSS" },
  { value: "react",        label: "React" },
  { value: "nodejs",       label: "Node.js" },
  { value: "git",          label: "Git" },
  { value: "terminal",     label: "Terminal" },
  { value: "algorithms",   label: "Algoritmos" },
  { value: "oop",          label: "OOP" },
  { value: "async",        label: "Async" },
  { value: "rest",         label: "REST/HTTP" },
  { value: "networks",     label: "Redes" },
  { value: "architecture", label: "Arquitetura" },
  { value: "sql",          label: "SQL" },
  { value: "docker",       label: "Docker" },
  { value: "security",     label: "Segurança" },
  { value: "cleancode",    label: "Clean Code" },
  { value: "career",       label: "Carreira" },
];
