export type GlossaryCategory = "python" | "typescript" | "sql" | "http" | "git" | "geral";

export interface GlossaryTerm {
  id: string;
  term: string;
  category: GlossaryCategory;
  short: string;
  detail: string;
  example?: string;
}

export const categoryMeta: Record<GlossaryCategory, { label: string; color: string }> = {
  python:     { label: "Python",     color: "#4db3ff" },
  typescript: { label: "TypeScript", color: "#3178c6" },
  sql:        { label: "SQL",        color: "#f59e0b" },
  http:       { label: "HTTP/REST",  color: "#34d399" },
  git:        { label: "Git",        color: "#f97316" },
  geral:      { label: "Geral",      color: "#a78bfa" },
};

export const glossaryTerms: GlossaryTerm[] = [
  // ── PYTHON ──
  { id: "py-1",  category: "python",     term: "List Comprehension",   short: "Criação concisa de listas com expressão inline",        detail: "Permite construir listas aplicando uma expressão a cada elemento de um iterável, opcionalmente filtrando com if.", example: "[x**2 for x in range(10) if x % 2 == 0]" },
  { id: "py-2",  category: "python",     term: "Decorator",            short: "Função que envolve e modifica outra função",            detail: "Um decorator recebe uma função como argumento e retorna uma nova função com comportamento adicional. Usado com @sintaxe.", example: "@app.get('/items')\ndef get_items(): ..." },
  { id: "py-3",  category: "python",     term: "Generator",            short: "Função que produz valores sob demanda com yield",        detail: "Generators são iteradores lazy — calculam o próximo valor apenas quando solicitado, economizando memória.", example: "def fib():\n  a, b = 0, 1\n  while True:\n    yield a\n    a, b = b, a+b" },
  { id: "py-4",  category: "python",     term: "Context Manager",      short: "Protocolo with/as para gerenciar recursos",             detail: "Implementado via __enter__ e __exit__, garante que recursos (arquivos, conexões) sejam fechados mesmo com exceções.", example: "with open('file.txt') as f:\n  data = f.read()" },
  { id: "py-5",  category: "python",     term: "Dunder / Magic Method", short: "Métodos especiais com duplo underscore (__init__ etc.)", detail: "Permitem sobrescrever comportamentos built-in: __str__ para representação, __len__ para len(), __eq__ para ==.", example: "def __repr__(self):\n  return f'User({self.name!r})'" },
  { id: "py-6",  category: "python",     term: "Type Hints",           short: "Anotações de tipo opcionais (PEP 484)",                 detail: "Não são enforçadas em runtime, mas permitem verificação estática com mypy e melhoram legibilidade.", example: "def greet(name: str) -> str:\n  return f'Hello {name}'" },
  { id: "py-7",  category: "python",     term: "GIL",                  short: "Global Interpreter Lock — limita threads em CPython",  detail: "O GIL impede que múltiplas threads Python executem bytecode simultaneamente. Para paralelismo real, use multiprocessing ou asyncio.", example: "" },
  { id: "py-8",  category: "python",     term: "asyncio / async-await", short: "Concorrência cooperativa com event loop",              detail: "Permite executar múltiplas coroutines concorrentemente em uma única thread. Ideal para I/O-bound (HTTP, DB).", example: "async def fetch(url):\n  async with aiohttp.ClientSession() as s:\n    return await s.get(url)" },
  { id: "py-9",  category: "python",     term: "Virtual Environment",  short: "Ambiente Python isolado por projeto",                  detail: "Cria uma cópia isolada do Python com suas próprias dependências, evitando conflitos entre projetos.", example: "python -m venv .venv\nsource .venv/bin/activate" },
  { id: "py-10", category: "python",     term: "dataclass",            short: "Decorator que gera __init__, __repr__ e __eq__ automaticamente", detail: "Reduz boilerplate para classes de dados simples. Suporta fields com default, frozen (imutável) e slots.", example: "@dataclass\nclass Point:\n  x: float\n  y: float" },
  { id: "py-11", category: "python",     term: "Pydantic",             short: "Validação de dados com type hints em runtime",          detail: "BaseModel do Pydantic valida e parseia dados automaticamente. Usado extensivamente no FastAPI.", example: "class User(BaseModel):\n  name: str\n  age: int" },
  { id: "py-12", category: "python",     term: "pytest",               short: "Framework de testes mais popular do Python",           detail: "Descobre testes automaticamente (arquivos test_*.py), suporta fixtures, parametrize e plugins.", example: "def test_sum():\n  assert sum([1,2,3]) == 6" },

  // ── TYPESCRIPT ──
  { id: "ts-1",  category: "typescript", term: "Union Type",           short: "Tipo que pode ser A ou B",                             detail: "string | number aceita ambos. Narrowing com typeof/instanceof determina o tipo em cada branch.", example: "type ID = string | number\nfunction getId(id: ID) { ... }" },
  { id: "ts-2",  category: "typescript", term: "Interface vs Type",    short: "Interface é extensível; type alias é mais flexível",   detail: "Interfaces podem ser merged (declaration merging) e são preferidas para objetos públicos de API. Types suportam unions, intersections e mapped types.", example: "interface User { name: string }\ntype Point = { x: number; y: number }" },
  { id: "ts-3",  category: "typescript", term: "Generics",             short: "Tipos parametrizados com <T>",                         detail: "Permitem escrever código reutilizável que funciona com qualquer tipo, mantendo type safety.", example: "function identity<T>(arg: T): T { return arg }" },
  { id: "ts-4",  category: "typescript", term: "keyof / typeof",       short: "Operadores de tipo para reflexão",                     detail: "keyof extrai as chaves de um tipo como union. typeof captura o tipo de um valor em tempo de compilação.", example: "type Keys = keyof { a: 1; b: 2 } // 'a' | 'b'" },
  { id: "ts-5",  category: "typescript", term: "Utility Types",        short: "Tipos genéricos built-in: Partial, Pick, Omit, etc.",  detail: "Partial<T> torna todos os campos opcionais. Pick/Omit selecionam campos. Record cria dicionários tipados.", example: "type PatchUser = Partial<Pick<User, 'name' | 'email'>>" },
  { id: "ts-6",  category: "typescript", term: "as const",             short: "Congela valores como literais readonly",               detail: "Impede widening: ['a', 'b'] vira readonly ['a', 'b'] em vez de string[].", example: "const ROLES = ['admin', 'user'] as const\ntype Role = typeof ROLES[number]" },
  { id: "ts-7",  category: "typescript", term: "Discriminated Union",  short: "Union com campo discriminante para narrowing seguro",  detail: "Um campo literal comum (type: 'circle' | 'square') permite ao TypeScript narrowar o tipo em switch/if.", example: "type Shape = { kind: 'circle'; r: number } | { kind: 'square'; side: number }" },
  { id: "ts-8",  category: "typescript", term: "Declaration Merging",  short: "Duas interfaces com mesmo nome são fundidas automaticamente", detail: "Útil para estender tipos de bibliotecas sem editar arquivos externos (module augmentation).", example: "interface Window { myLib: typeof myLib }" },
  { id: "ts-9",  category: "typescript", term: "Mapped Type",          short: "Transforma um tipo mapeando suas chaves",              detail: "{ [K in keyof T]: ... } itera sobre as chaves de T aplicando uma transformação.", example: "type Optional<T> = { [K in keyof T]?: T[K] }" },
  { id: "ts-10", category: "typescript", term: "Strict Mode",          short: "Conjunto de verificações rigorosas do compilador",     detail: "strictNullChecks, noImplicitAny, strictFunctionTypes etc. Essencial em projetos novos.", example: "// tsconfig.json\n{ \"compilerOptions\": { \"strict\": true } }" },

  // ── SQL ──
  { id: "sql-1", category: "sql",        term: "JOIN",                 short: "Combina linhas de duas tabelas por uma condição",       detail: "INNER retorna apenas correspondências. LEFT mantém todas as linhas da esquerda. FULL OUTER mantém todas.", example: "SELECT u.name, o.total\nFROM users u\nJOIN orders o ON u.id = o.user_id" },
  { id: "sql-2", category: "sql",        term: "Index",                short: "Estrutura auxiliar que acelera consultas",              detail: "Um índice B-tree em uma coluna de filtro/join pode reduzir leitura de O(n) para O(log n). Tem custo em writes.", example: "CREATE INDEX idx_email ON users(email)" },
  { id: "sql-3", category: "sql",        term: "Transaction / ACID",   short: "Bloco de operações atômicas com garantias ACID",        detail: "Atomicity, Consistency, Isolation, Durability. BEGIN/COMMIT envolve operações; ROLLBACK desfaz em caso de erro.", example: "BEGIN;\nUPDATE accounts SET bal = bal - 100 WHERE id = 1;\nUPDATE accounts SET bal = bal + 100 WHERE id = 2;\nCOMMIT;" },
  { id: "sql-4", category: "sql",        term: "CTE (WITH clause)",    short: "Subquery nomeada e reutilizável na mesma query",        detail: "Common Table Expression melhora legibilidade e permite recursão (WITH RECURSIVE) para hierarquias.", example: "WITH ranked AS (\n  SELECT *, ROW_NUMBER() OVER (ORDER BY score DESC) AS rn FROM scores\n)\nSELECT * FROM ranked WHERE rn <= 10" },
  { id: "sql-5", category: "sql",        term: "Window Function",      short: "Agregação sem colapsar linhas (OVER clause)",          detail: "ROW_NUMBER, RANK, LAG, LEAD, SUM OVER PARTITION — calculam sobre um conjunto de linhas sem agrupar o resultado.", example: "SELECT name, salary,\n  AVG(salary) OVER (PARTITION BY dept) AS dept_avg\nFROM employees" },
  { id: "sql-6", category: "sql",        term: "Normalization",        short: "Organizar dados para eliminar redundância",             detail: "1NF: atômico. 2NF: sem dependência parcial. 3NF: sem dependência transitiva. Desnormalizar para leitura intensiva.", example: "" },
  { id: "sql-7", category: "sql",        term: "EXPLAIN / EXPLAIN ANALYZE", short: "Mostra o plano de execução de uma query",        detail: "Identifica sequential scans, index usage, join order e custos estimados. ANALYZE executa a query e mostra tempos reais.", example: "EXPLAIN ANALYZE SELECT * FROM orders WHERE user_id = 42" },

  // ── HTTP ──
  { id: "http-1", category: "http",      term: "HTTP Methods",         short: "GET, POST, PUT, PATCH, DELETE — semântica de operação", detail: "GET lê, POST cria, PUT substitui completo, PATCH atualiza parcial, DELETE remove. Idempotência: GET/PUT/DELETE são idempotentes.", example: "PUT /users/1  → substitui inteiro\nPATCH /users/1 → atualiza campos" },
  { id: "http-2", category: "http",      term: "Status Codes",         short: "2xx sucesso, 4xx erro cliente, 5xx erro servidor",     detail: "200 OK, 201 Created, 204 No Content, 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 422 Unprocessable, 500 Internal.", example: "" },
  { id: "http-3", category: "http",      term: "REST Constraints",     short: "6 princípios do estilo arquitetural REST",             detail: "Stateless, client-server, cacheable, uniform interface, layered system, code-on-demand (opcional). O mais crítico: stateless — servidor não guarda estado de sessão.", example: "" },
  { id: "http-4", category: "http",      term: "JWT",                  short: "JSON Web Token — autenticação stateless",             detail: "Header.Payload.Signature encodados em base64. O servidor assina com secret/chave privada. Não armazene dados sensíveis no payload (é decodificável).", example: "Authorization: Bearer eyJhbGci..." },
  { id: "http-5", category: "http",      term: "CORS",                 short: "Cross-Origin Resource Sharing — controle de acesso",  detail: "Browser bloqueia requests cross-origin por padrão. Servidor deve responder com Access-Control-Allow-Origin para liberar.", example: "Access-Control-Allow-Origin: https://meuapp.com" },
  { id: "http-6", category: "http",      term: "Rate Limiting",        short: "Limite de requests por janela de tempo",              detail: "Protege a API de abuso. Implementado com contadores por IP/token em Redis. 429 Too Many Requests quando excedido.", example: "X-RateLimit-Limit: 100\nX-RateLimit-Remaining: 42" },

  // ── GIT ──
  { id: "git-1", category: "git",        term: "Rebase vs Merge",      short: "Rebase reescreve história; merge preserva",           detail: "Rebase aplica commits em cima de outra branch, criando histórico linear. Merge cria um commit de merge. Nunca rebase branches públicas.", example: "git rebase main     # reaplica commits\ngit merge feature   # cria merge commit" },
  { id: "git-2", category: "git",        term: "Cherry-pick",          short: "Aplica um commit específico em outra branch",         detail: "Útil para backport de fixes. Cria um novo commit com o mesmo diff, mas hash diferente.", example: "git cherry-pick abc1234" },
  { id: "git-3", category: "git",        term: "Stash",                short: "Salva mudanças sem commitar para uso posterior",      detail: "git stash push salva working directory + index. git stash pop restaura. Útil para trocar de branch com trabalho em progresso.", example: "git stash push -m 'WIP feature'\ngit stash pop" },
  { id: "git-4", category: "git",        term: "HEAD",                 short: "Ponteiro para o commit atual (ou branch atual)",      detail: "HEAD normalmente aponta para uma branch (attached). HEAD detachado aponta direto para um commit — cuidado ao criar commits nesse estado.", example: "git log --oneline -1  # mostra onde HEAD está" },
  { id: "git-5", category: "git",        term: "git bisect",           short: "Busca binária para encontrar o commit que introduziu um bug", detail: "Divide o histórico ao meio, você marca good/bad, e o Git encontra o commit problemático em O(log n) passos.", example: "git bisect start\ngit bisect bad HEAD\ngit bisect good v1.0" },

  // ── GERAL ──
  { id: "gen-1", category: "geral",      term: "Big O Notation",       short: "Mede crescimento de tempo/espaço em função do input", detail: "O(1) constante, O(log n) logarítmico, O(n) linear, O(n log n) quasi-linear, O(n²) quadrático. Sempre analise o pior caso.", example: "// O(n²) — nested loop\nfor i in arr:\n  for j in arr: ..." },
  { id: "gen-2", category: "geral",      term: "SOLID",                short: "5 princípios de design OO para código manutenível",   detail: "Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion. Cada princípio reduz um tipo de rigidez.", example: "" },
  { id: "gen-3", category: "geral",      term: "DRY / WET",            short: "Don't Repeat Yourself — abstraia duplicação",         detail: "WET = Write Everything Twice (anti-padrão). Mas atenção: premature abstraction é pior que duplicação. Espere 3+ ocorrências.", example: "" },
  { id: "gen-4", category: "geral",      term: "CI/CD",                short: "Integração e entrega contínua de código",             detail: "CI: build + testes a cada push. CD: deploy automático após CI verde. Elimina integrações manuais e reduce risco de release.", example: "push → GitHub Actions → test → build → deploy" },
  { id: "gen-5", category: "geral",      term: "Docker",               short: "Empacota app + dependências em um container",         detail: "Image é o template imutável. Container é a instância rodando. Dockerfile descreve como construir a image.", example: "FROM python:3.12-slim\nCOPY . .\nRUN pip install -r requirements.txt\nCMD ['python', 'app.py']" },
  { id: "gen-6", category: "geral",      term: "Idempotência",         short: "Executar N vezes dá o mesmo resultado que 1 vez",     detail: "Crítico em APIs REST (PUT, DELETE) e sistemas distribuídos. Permite retry seguro sem efeitos colaterais duplicados.", example: "DELETE /users/1 — segunda chamada retorna 404, mas estado final é o mesmo" },
  { id: "gen-7", category: "geral",      term: "Race Condition",       short: "Bug causado por timing imprevisível entre threads/processos", detail: "Dois agentes leem, modificam e escrevem o mesmo dado sem sincronização — o último a escrever vence, corrompendo estado.", example: "" },
  { id: "gen-8", category: "geral",      term: "Cache",                short: "Armazenamento temporário para acelerar leituras",     detail: "Hit: dado encontrado. Miss: não encontrado, busca na origem. Invalidação é o problema difícil: quando expirar/limpar.", example: "Redis: SET user:1 '{...}' EX 300" },
];
